/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c47d5bc7-65d4-42d6-80d9-373eba81a993",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_OkXrhn8j4",
    "aws_user_pools_web_client_id": "22vp3sgmr06fr7vaja6dc680pq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://26h3mxahl5dirkkxlwe6tyejju.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
